<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Clientes_dalvian_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get clientes_dalvian by id
     */
    function get_clientes_dalvian($id)
    {
        return $this->db->get_where('clientes_dalvian',array('id'=>$id))->row_array();
    }
    
    /*
     * Get all clientes_dalvian count
     */
    function get_all_clientes_dalvian_count()
    {
        $this->db->from('clientes_dalvian');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all clientes_dalvian
     */
    function get_all_clientes_dalvian($params = array())
    {
        $this->db->order_by('id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('clientes_dalvian')->result_array();
    }
        
    /*
     * function to add new clientes_dalvian
     */
    function add_clientes_dalvian($params)
    {
        $this->db->insert('clientes_dalvian',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update clientes_dalvian
     */
    function update_clientes_dalvian($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('clientes_dalvian',$params);
    }
    
    /*
     * function to delete clientes_dalvian
     */
    function delete_clientes_dalvian($id)
    {
        return $this->db->delete('clientes_dalvian',array('id'=>$id));
    }
}
